apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-local
  namespace: argocd
  labels:
    environment: local
    gitops.254carbon.io/promotion-tier: local
  annotations:
    gitops.254carbon.io/promotion-source: none
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git://git-mirror.argocd.svc.cluster.local/infra.git
    targetRevision: main
    path: k8s/overlays/local
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
