apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - namespace.yaml
  - install.yaml
  - application-local.yaml
  - applicationset-environments.yaml

patchesStrategicMerge:
  - resource-requests.yaml

labels:
  - pairs:
      tier: platform
      domain: gitops
