apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: platform-core

resources:
  - keycloak.yaml

labels:
  - pairs:
      app.kubernetes.io/name: keycloak
      app.kubernetes.io/part-of: "254carbon"
      tier: platform
      domain: access
