apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observability

resources:
  - otel-collector.yaml
  - collector-config.yaml

labels:
  - pairs:
      app.kubernetes.io/name: otel-collector
      app.kubernetes.io/part-of: "254carbon"
      tier: platform
      domain: observability
