apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ml

resources:
  - helm-chart.yaml
  - mlflow-ingress.yaml

labels:
  - pairs:
      app.kubernetes.io/name: mlflow
      app.kubernetes.io/part-of: "254carbon"
      tier: platform
      domain: ml

patchesStrategicMerge:
  - sa-imagepullsecrets.yaml
