apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ../../platform/clickhouse
  - ../../platform/postgresql
  - ../../platform/redis
  - ../../platform/kafka
  - ../../platform/minio
  - ../../platform/keycloak
  - ../../platform/mlflow
  - ../../platform/metrics-stack
  - ../../platform/otel
  - ../../platform/ingress-nginx
  - ../../platform/backup-jobs
  - ../../platform/backports
  - ../../platform/kyverno
  - ../../platform/gatekeeper
  - ../../platform/trivy-operator
  - ../../platform/argocd

labels:
  - pairs:
      environment: dev
      app.kubernetes.io/managed-by: "kustomize"

patches:
  - path: dev-patches.yaml

patchesStrategicMerge:
  - argocd-labels.yaml
