apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: "254carbon"
  security.254carbon.com/component: kyverno

resources:
  - https://github.com/kyverno/kyverno/releases/download/v1.15.2/install.yaml
  - policies/require-signed-images.yaml
